#!/usr/bin/env python3
"""Build and verify a hash-locked offline Codex SDK runtime directory."""

from __future__ import annotations

import argparse
from email.parser import Parser
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
from typing import Iterable
import zipfile


LOCK_NAME = 'requirements-codex.lock'
MANIFEST_NAME = 'codex-runtime-manifest.json'
WHEELHOUSE_NAME = 'wheelhouse'


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def _normalize_name(value: str) -> str:
    return value.strip().lower().replace('_', '-').replace('.', '-')


def _wheel_identity(path: Path) -> tuple[str, str]:
    if path.suffix != '.whl':
        raise ValueError(f'non-wheel artifact is forbidden: {path.name}')
    with zipfile.ZipFile(path) as wheel:
        metadata_names = [
            name for name in wheel.namelist()
            if name.endswith('.dist-info/METADATA')
        ]
        if len(metadata_names) != 1:
            raise ValueError(f'wheel has invalid METADATA layout: {path.name}')
        metadata_info = wheel.getinfo(metadata_names[0])
        if metadata_info.file_size > 1024 * 1024:
            raise ValueError(f'wheel METADATA is too large: {path.name}')
        metadata = Parser().parsestr(
            wheel.read(metadata_info).decode('utf-8', errors='strict')
        )
    name = _normalize_name(metadata.get('Name', ''))
    version = metadata.get('Version', '').strip()
    if (
        not re.fullmatch(r'[a-z0-9][a-z0-9-]*', name)
        or not version
        or any(char.isspace() for char in version)
    ):
        raise ValueError(f'wheel identity is invalid: {path.name}')
    return name, version


def _artifacts(wheelhouse: Path) -> list[dict[str, str]]:
    wheels = sorted(wheelhouse.iterdir(), key=lambda item: item.name.casefold())
    if not wheels:
        raise ValueError('wheelhouse is empty')
    result = []
    seen: set[str] = set()
    for wheel in wheels:
        if wheel.is_symlink() or not wheel.is_file():
            raise ValueError(f'wheelhouse contains a non-file: {wheel.name}')
        name, version = _wheel_identity(wheel)
        if name in seen:
            raise ValueError(f'wheelhouse contains duplicate package: {name}')
        seen.add(name)
        result.append({
            'name': name,
            'version': version,
            'filename': wheel.name,
            'sha256': _sha256(wheel),
        })
    return result


def _lock_text(artifacts: Iterable[dict[str, str]]) -> str:
    lines = [
        '# Generated by ops/codex_runtime_release.py; do not edit.',
        '# Every package and transitive dependency is version/hash locked.',
    ]
    for artifact in sorted(artifacts, key=lambda item: item['name']):
        lines.append(
            f"{artifact['name']}=={artifact['version']} "
            f"--hash=sha256:{artifact['sha256']}"
        )
    return '\n'.join(lines) + '\n'


def write_contract(
    runtime: Path,
    *,
    sdk_version: str,
    platform: str,
    python_version: str,
    implementation: str,
    abi: str,
) -> dict:
    wheelhouse = runtime / WHEELHOUSE_NAME
    artifacts = _artifacts(wheelhouse)
    versions = {item['name']: item['version'] for item in artifacts}
    for package in ('openai-codex', 'openai-codex-cli-bin'):
        if versions.get(package) != sdk_version:
            raise ValueError(
                f'{package} must be present at the approved SDK version '
                f'{sdk_version}'
            )
    lock_path = runtime / LOCK_NAME
    lock_path.write_text(_lock_text(artifacts), encoding='utf-8', newline='\n')
    manifest = {
        'schema': 1,
        'sdk_version': sdk_version,
        'target': {
            'platform': platform,
            'python_version': python_version,
            'implementation': implementation,
            'abi': abi,
        },
        'requirements': LOCK_NAME,
        'requirements_sha256': _sha256(lock_path),
        'wheelhouse': WHEELHOUSE_NAME,
        'artifacts': artifacts,
    }
    (runtime / MANIFEST_NAME).write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + '\n',
        encoding='utf-8',
        newline='\n',
    )
    return manifest


def verify_contract(runtime: Path) -> dict:
    manifest_path = runtime / MANIFEST_NAME
    if manifest_path.stat().st_size > 2 * 1024 * 1024:
        raise ValueError('Codex runtime manifest is too large')
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    if manifest.get('schema') != 1:
        raise ValueError('unsupported Codex runtime manifest schema')
    if (
        manifest.get('requirements') != LOCK_NAME
        or manifest.get('wheelhouse') != WHEELHOUSE_NAME
    ):
        raise ValueError('manifest paths are not canonical')
    lock_path = runtime / LOCK_NAME
    wheelhouse = runtime / WHEELHOUSE_NAME
    if lock_path.stat().st_size > 2 * 1024 * 1024:
        raise ValueError('requirements lock is too large')
    if _sha256(lock_path) != manifest.get('requirements_sha256'):
        raise ValueError('requirements lock SHA-256 mismatch')
    actual = _artifacts(wheelhouse)
    if actual != manifest.get('artifacts'):
        raise ValueError('wheelhouse artifact set or SHA-256 mismatch')
    if lock_path.read_text(encoding='utf-8') != _lock_text(actual):
        raise ValueError('requirements lock content does not match wheelhouse')
    sdk_version = str(manifest.get('sdk_version') or '')
    versions = {item['name']: item['version'] for item in actual}
    if versions.get('openai-codex') != sdk_version:
        raise ValueError('openai-codex version does not match manifest')
    if versions.get('openai-codex-cli-bin') != sdk_version:
        raise ValueError('Codex CLI runtime version does not match SDK')
    return manifest


def build(config_path: Path, output: Path, python: str) -> dict:
    config = json.loads(config_path.read_text(encoding='utf-8'))
    required = (
        'sdk_version', 'platform', 'python_version', 'implementation', 'abi'
    )
    if any(not str(config.get(key) or '').strip() for key in required):
        raise ValueError('release config is incomplete')
    if output.exists() and any(output.iterdir()):
        raise ValueError(f'output directory is not empty: {output}')
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix='.codex-runtime-', dir=output.parent
    ) as temp_name:
        temp = Path(temp_name)
        wheelhouse = temp / WHEELHOUSE_NAME
        wheelhouse.mkdir()
        command = [
            python, '-m', 'pip', 'download',
            '--disable-pip-version-check',
            '--only-binary=:all:',
            '--dest', str(wheelhouse),
            '--platform', config['platform'],
            '--python-version', config['python_version'],
            '--implementation', config['implementation'],
            '--abi', config['abi'],
            f"openai-codex=={config['sdk_version']}",
        ]
        subprocess.run(command, check=True)
        write_contract(temp, **config)
        verify_contract(temp)
        if output.exists():
            output.rmdir()
        shutil.move(str(temp), str(output))
    return verify_contract(output)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='command', required=True)
    build_parser = subparsers.add_parser('build')
    build_parser.add_argument(
        '--config', type=Path,
        default=Path(__file__).with_name('codex-runtime-linux-x86_64.json'),
    )
    build_parser.add_argument('--output', type=Path, required=True)
    build_parser.add_argument('--python', default=sys.executable)
    verify_parser = subparsers.add_parser('verify')
    verify_parser.add_argument('--runtime', type=Path, required=True)
    args = parser.parse_args(argv)
    if args.command == 'build':
        manifest = build(args.config.resolve(), args.output.resolve(), args.python)
    else:
        manifest = verify_contract(args.runtime.resolve())
    print(json.dumps({
        'sdk_version': manifest['sdk_version'],
        'requirements_sha256': manifest['requirements_sha256'],
        'artifact_count': len(manifest['artifacts']),
    }, separators=(',', ':')))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
